# Site settings
title: Insane driver
email: insanedriverofficial@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  Alternative metal band.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://insanedriver.com.br" # the base hostname & protocol for your site
twitter_username: insanedriver
facebook_username:  projectrocker


# Build settings
markdown: kramdown

safe: true
lsi: false
site: created
